---
- name: Install Nginx
  apt:
    name: nginx
    state: present
    update_cache: yes
  tags:
    - nginx

- name: Configure Load Balancer
  template:
    src: load_balancer.conf.j2
    dest: /etc/nginx/conf.d/load_balancer.conf
  when: inventory_hostname == "webserver3"
  notify:
    - Restart Nginx
  tags:
    - load_balancer

- name: Create Web Server landing page
  copy:
    content: "{{ nginx_web_server_content }}"
    dest: /var/www/html/index.html
  when: inventory_hostname in groups['webservers']
  tags:
    - web_server


